export const BUILT_IN_SONGS = [
  {
    id: 'song_01',
    title: 'Un Mela Aasadhaan',
    artist: 'G.V. Prakash, Dhanush, Andrea',
    album: 'Aayirathil Oruvan',
    duration: 275,
    isBuiltIn: true,
    uri: require('../../assets/songs/song_01.mp3'),
    colorPalette: ['#EF4444', '#8B5CF6'],
  },
  {
    id: 'song_02',
    title: 'Maduraikku Pogathadi',
    artist: 'A.R. Rahman, Benny Dayal, Archith',
    album: 'Azhagiya Tamil Magan',
    duration: 320,
    isBuiltIn: true,
    uri: require('../../assets/songs/song_02.mp3'),
    colorPalette: ['#F59E0B', '#EF4444'],
  },
  {
    id: 'song_03',
    title: 'Idicha Pacharasi',
    artist: 'Vijay Antony, Ranjith, Sangeetha',
    album: 'Uthama Puthiran',
    duration: 290,
    isBuiltIn: true,
    uri: require('../../assets/songs/song_03.mp3'),
    colorPalette: ['#10B981', '#0EA5E9'],
  },
  {
    id: 'song_04',
    title: 'The Life of Ram (Journey)',
    artist: 'Govind Vasantha, Pradeep Kumar',
    album: 'Jaanu (96)',
    duration: 345,
    isBuiltIn: true,
    uri: require('../../assets/songs/song_04.mp3'),
    colorPalette: ['#6366F1', '#8B5CF6'],
  },
  {
    id: 'song_05',
    title: 'Siriki',
    artist: 'Harris Jayaraj, Senthil Ganesh',
    album: 'Kaappaan',
    duration: 285,
    isBuiltIn: true,
    uri: require('../../assets/songs/song_05.mp3'),
    colorPalette: ['#8B5CF6', '#D946EF'],
  },
  {
    id: 'song_06',
    title: 'Adada Mazhaida',
    artist: 'Yuvan Shankar Raja, Rahul Nambiar',
    album: 'Paiyaa',
    duration: 250,
    isBuiltIn: true,
    uri: require('../../assets/songs/song_06.mp3'),
    colorPalette: ['#0EA5E9', '#6366F1'],
  },
  {
    id: 'song_07',
    title: 'Pazhaya Soru',
    artist: 'Srikanth Deva, Namitha, Jiiva',
    album: 'Thirunaal',
    duration: 210,
    isBuiltIn: true,
    uri: require('../../assets/songs/song_07.mp3'),
    colorPalette: ['#D946EF', '#F59E0B'],
  },
  {
    id: 'song_08',
    title: 'Pesum Mazhai',
    artist: 'Ashley Milred, Farhash, Malavika',
    album: 'Pesum Mazhai',
    duration: 235,
    isBuiltIn: true,
    uri: require('../../assets/songs/song_08.mp3'),
    colorPalette: ['#0EA5E9', '#D946EF'],
  },
  {
    id: 'song_09',
    title: 'Piriyadha Enna',
    artist: 'Vivek - Mervin, Vijay Yesudas',
    album: 'Pattas',
    duration: 260,
    isBuiltIn: true,
    uri: require('../../assets/songs/song_09.mp3'),
    colorPalette: ['#6366F1', '#10B981'],
  },
  {
    id: 'song_10',
    title: 'Un Mele Oru Kannu',
    artist: 'D. Imman, Jithin Raj, Jyoti Nooran',
    album: 'Rajinimurugan',
    duration: 270,
    isBuiltIn: true,
    uri: require('../../assets/songs/song_10.mp3'),
    colorPalette: ['#8B5CF6', '#F59E0B'],
  },
  {
    id: 'song_11',
    title: 'Koodamela Koodavechi',
    artist: 'D. Imman, V.V. Prassanna, Vandana',
    album: 'Rummy',
    duration: 280,
    isBuiltIn: true,
    uri: require('../../assets/songs/song_11.mp3'),
    colorPalette: ['#10B981', '#D946EF'],
  },
  {
    id: 'song_12',
    title: 'Kangal Irandal',
    artist: 'James Vasanthan, Belly Raj, Deepa',
    album: 'Subramaniapuram',
    duration: 315,
    isBuiltIn: true,
    uri: require('../../assets/songs/song_12.mp3'),
    colorPalette: ['#F59E0B', '#6366F1'],
  },
  {
    id: 'song_13',
    title: 'Thaaliyae Thevaiyillai',
    artist: 'Yuvan Shankar Raja, Hariharan',
    album: 'Thaamirabharani',
    duration: 295,
    isBuiltIn: true,
    uri: require('../../assets/songs/song_13.mp3'),
    colorPalette: ['#EF4444', '#10B981'],
  },
  {
    id: 'song_14',
    title: 'Thean Kudika',
    artist: 'TeeJay ft. Pragathi Guruprasad',
    album: 'Thean Kudika',
    duration: 215,
    isBuiltIn: true,
    uri: require('../../assets/songs/song_14.mp3'),
    colorPalette: ['#0EA5E9', '#8B5CF6'],
  },
  {
    id: 'song_15',
    title: 'Nee Otha Sollu Sollu',
    artist: 'Vijay Antony, Naresh Iyer',
    album: 'Aval Peyar Tamilarasi',
    duration: 265,
    isBuiltIn: true,
    uri: require('../../assets/songs/song_15.mp3'),
    colorPalette: ['#D946EF', '#6366F1'],
  },
  {
    id: 'song_16',
    title: 'Usure Needhan Pulla',
    artist: 'G.V. Prakash Kumar, Mathimaran',
    album: 'Mandaadi',
    duration: 245,
    isBuiltIn: true,
    uri: require('../../assets/songs/song_16.mp3'),
    colorPalette: ['#EC4899', '#8B5CF6'],
  },
];
