import { Song, Album, Artist, Playlist } from '../types/music';

export const ARTWORK_COLORS: [string, string][] = [
  ['#6366F1', '#8B5CF6'],
  ['#8B5CF6', '#D946EF'],
  ['#0EA5E9', '#6366F1'],
  ['#10B981', '#0EA5E9'],
  ['#F59E0B', '#EF4444'],
  ['#EF4444', '#8B5CF6'],
  ['#D946EF', '#F59E0B'],
  ['#6366F1', '#10B981'],
  ['#0EA5E9', '#D946EF'],
  ['#8B5CF6', '#F59E0B'],
  ['#10B981', '#D946EF'],
  ['#F59E0B', '#6366F1'],
  ['#EF4444', '#10B981'],
  ['#0EA5E9', '#8B5CF6'],
  ['#D946EF', '#6366F1'],
];

/**
 * 15 Built-in Tamil Songs bundled directly into APK
 * These files are stored in:
 * - android/app/src/main/res/raw/song_01.mp3 ... song_15.mp3
 * - android/app/src/main/assets/songs/song_01.mp3 ... song_15.mp3
 * - src/assets/songs/song_01.mp3 ... song_15.mp3
 * Guaranteed to play offline immediately after installing the APK on any phone!
 */
export const BUILT_IN_SONGS: Song[] = [
  {
    id: 'song_01',
    title: 'Un Mela Aasadhaan',
    artist: 'G.V. Prakash, Dhanush, Andrea',
    album: 'Aayirathil Oruvan',
    duration: 275,
    isBuiltIn: true,
    uri: 'asset:/songs/song_01.mp3',
    colorPalette: ['#EF4444', '#8B5CF6'],
    lyrics: [
      'Un mela aasadhaan anbaala paasathan',
      'Unnaala thaan naan vaazhuren uyir kaathirukken',
      'Kangal paartha nodiyil en manam unnai thodangiyadho',
      'En idhayathil un perai ezhudhi vaithen',
    ],
  },
  {
    id: 'song_02',
    title: 'Maduraikku Pogathadi',
    artist: 'A.R. Rahman, Benny Dayal, Archith',
    album: 'Azhagiya Tamil Magan',
    duration: 320,
    isBuiltIn: true,
    uri: 'asset:/songs/song_02.mp3',
    colorPalette: ['#F59E0B', '#EF4444'],
    lyrics: [
      'Maduraikku pogathadi angayum unnai thodarum',
      'Azhagiya thamizh magane un parvai thaakudhe',
      'Pattu poovai polae ennai thaalaatta vaaraayo',
    ],
  },
  {
    id: 'song_03',
    title: 'Idicha Pacharasi',
    artist: 'Vijay Antony, Ranjith, Sangeetha',
    album: 'Uthama Puthiran',
    duration: 290,
    isBuiltIn: true,
    uri: 'asset:/songs/song_03.mp3',
    colorPalette: ['#10B981', '#0EA5E9'],
    lyrics: [
      'Idicha pacharasi podi pottu vachirukken',
      'Unna paatha pothum manasu thaavudhe',
      'Aattam pottu aadalam vaadi en chellakkili',
    ],
  },
  {
    id: 'song_04',
    title: 'The Life of Ram (Journey)',
    artist: 'Govind Vasantha, Pradeep Kumar',
    album: 'Jaanu (96)',
    duration: 345,
    isBuiltIn: true,
    uri: 'asset:/songs/song_04.mp3',
    colorPalette: ['#6366F1', '#8B5CF6'],
    lyrics: [
      'Iravin thunaiyil thanimaiyil oru payanam',
      'Yaaro ivan yaaro kadalil thavazhum alaiyo',
      'Kaatrin kural kettu en vazhiye pogiren',
      'Vaanam engum paranthu kaatril karaiyiren',
    ],
  },
  {
    id: 'song_05',
    title: 'Siriki',
    artist: 'Harris Jayaraj, Senthil Ganesh',
    album: 'Kaappaan',
    duration: 285,
    isBuiltIn: true,
    uri: 'asset:/songs/song_05.mp3',
    colorPalette: ['#8B5CF6', '#D946EF'],
    lyrics: [
      'Siriki siriki sirichu mayakkura vaadi',
      'Kaappaan vanthu kaappaathuvaan paarudi',
      'Nee siricha pothum nattil malai peiyum',
    ],
  },
  {
    id: 'song_06',
    title: 'Adada Mazhaida',
    artist: 'Yuvan Shankar Raja, Rahul Nambiar',
    album: 'Paiyaa',
    duration: 250,
    isBuiltIn: true,
    uri: 'asset:/songs/song_06.mp3',
    colorPalette: ['#0EA5E9', '#6366F1'],
    lyrics: [
      'Adada mazhaida ada mazhaida',
      'Azhaga azhaga vizhugiradhae',
      'En kannodu un mugam thonrudhe',
      'Mazhai neeril un ninaivugal nanaiyudhe',
    ],
  },
  {
    id: 'song_07',
    title: 'Pazhaya Soru',
    artist: 'Srikanth Deva, Namitha, Jiiva',
    album: 'Thirunaal',
    duration: 210,
    isBuiltIn: true,
    uri: 'asset:/songs/song_07.mp3',
    colorPalette: ['#D946EF', '#F59E0B'],
    lyrics: [
      'Pazhaya soru pachamilagaai',
      'Thirunaal vanthachu thiruvizha aatam podu',
      'Getti melam kotti varum namma aattam',
    ],
  },
  {
    id: 'song_08',
    title: 'Pesum Mazhai',
    artist: 'Ashley Milred, Farhash, Malavika',
    album: 'Pesum Mazhai',
    duration: 235,
    isBuiltIn: true,
    uri: 'asset:/songs/song_08.mp3',
    colorPalette: ['#0EA5E9', '#D946EF'],
    lyrics: [
      'Pesum mazhaiye en kanneer thudaikka vaayo',
      'Kaatril un swasam en nenjai theendudhe',
      'Mounathil pesa mudiyaadha mouna raagam',
    ],
  },
  {
    id: 'song_09',
    title: 'Piriyadha Enna',
    artist: 'Vivek - Mervin, Vijay Yesudas',
    album: 'Pattas',
    duration: 260,
    isBuiltIn: true,
    uri: 'asset:/songs/song_09.mp3',
    colorPalette: ['#6366F1', '#10B981'],
    lyrics: [
      'Piriyadha enna pirithu vitta kaalam',
      'Un ninaivil naanum vazhuren',
      'En uyirin paadhi neeye endru solladi',
    ],
  },
  {
    id: 'song_10',
    title: 'Un Mele Oru Kannu',
    artist: 'D. Imman, Jithin Raj, Jyoti Nooran',
    album: 'Rajinimurugan',
    duration: 270,
    isBuiltIn: true,
    uri: 'asset:/songs/song_10.mp3',
    colorPalette: ['#8B5CF6', '#F59E0B'],
    lyrics: [
      'Un mele oru kannu en nenjil oru ponnu',
      'Rajinimurugan vanthu kitta ninnu',
      'Aiyayo un paarvai katti ilukkudhe',
    ],
  },
  {
    id: 'song_11',
    title: 'Koodamela Koodavechi',
    artist: 'D. Imman, V.V. Prassanna, Vandana',
    album: 'Rummy',
    duration: 280,
    isBuiltIn: true,
    uri: 'asset:/songs/song_11.mp3',
    colorPalette: ['#10B981', '#D946EF'],
    lyrics: [
      'Koodamela koodavechi koodaloor poravalae',
      'Un kooda naanum vandhaa enna solvaaiyo',
      'Marudhani poothirukku un kooda serum pothu',
    ],
  },
  {
    id: 'song_12',
    title: 'Kangal Irandal',
    artist: 'James Vasanthan, Belly Raj, Deepa',
    album: 'Subramaniapuram',
    duration: 315,
    isBuiltIn: true,
    uri: 'asset:/songs/song_12.mp3',
    colorPalette: ['#F59E0B', '#6366F1'],
    lyrics: [
      'Kangal irandal un kangal irandal',
      'Ennai katti izhuthai izhuthai idhayathilae',
      'Aayiram aasaigal en nenjil poothadhe',
    ],
  },
  {
    id: 'song_13',
    title: 'Thaaliyae Thevaiyillai',
    artist: 'Yuvan Shankar Raja, Hariharan',
    album: 'Thaamirabharani',
    duration: 295,
    isBuiltIn: true,
    uri: 'asset:/songs/song_13.mp3',
    colorPalette: ['#EF4444', '#10B981'],
    lyrics: [
      'Thaaliyae thevaiyillai nee thaan en vaazhkai',
      'Nee illamal naan enge povaen',
      'Thaamirabharani aatril vizhundha thaamaraiye',
    ],
  },
  {
    id: 'song_14',
    title: 'Thean Kudika',
    artist: 'TeeJay ft. Pragathi Guruprasad',
    album: 'Thean Kudika',
    duration: 215,
    isBuiltIn: true,
    uri: 'asset:/songs/song_14.mp3',
    colorPalette: ['#0EA5E9', '#8B5CF6'],
    lyrics: [
      'Thean kudika vandha vandu naan',
      'Un udhattil thean thanthaaiye',
      'En idhayam un vasam aanadhu',
    ],
  },
  {
    id: 'song_15',
    title: 'Nee Otha Sollu Sollu',
    artist: 'Vijay Antony, Naresh Iyer',
    album: 'Aval Peyar Tamilarasi',
    duration: 265,
    isBuiltIn: true,
    uri: 'asset:/songs/song_15.mp3',
    colorPalette: ['#D946EF', '#6366F1'],
    lyrics: [
      'Nee otha sollu sollu manasa tharen',
      'Avan ivan kettalum unna thaane paarkiren',
      'Uyirukku uyir thara kaathirukken',
    ],
  },
  {
    id: 'song_16',
    title: 'Usure Needhan Pulla',
    artist: 'G.V. Prakash Kumar, Mathimaran',
    album: 'Mandaadi',
    duration: 245,
    isBuiltIn: true,
    uri: 'asset:/songs/song_16.mp3',
    colorPalette: ['#EC4899', '#8B5CF6'],
    lyrics: [
      'Usure needhan pulla en ulagame needhan pulla',
      'Unna thavira enakku vera aaru pulla',
      'Mandaadi kaatula un kooda vazhanum pulla',
    ],
  },
];

export const BUILT_IN_ALBUMS: Album[] = [
  { id: 'alb_1', title: 'Paiyaa', artist: 'Yuvan Shankar Raja', songCount: 1, artworkColors: ['#0EA5E9', '#6366F1'] },
  { id: 'alb_2', title: 'Rajinimurugan', artist: 'D. Imman', songCount: 1, artworkColors: ['#8B5CF6', '#F59E0B'] },
  { id: 'alb_3', title: 'Kaappaan', artist: 'Harris Jayaraj', songCount: 1, artworkColors: ['#8B5CF6', '#D946EF'] },
  { id: 'alb_4', title: 'Azhagiya Tamil Magan', artist: 'A.R. Rahman', songCount: 1, artworkColors: ['#F59E0B', '#EF4444'] },
  { id: 'alb_5', title: 'Aayirathil Oruvan', artist: 'G.V. Prakash', songCount: 1, artworkColors: ['#EF4444', '#8B5CF6'] },
  { id: 'alb_6', title: 'Subramaniapuram', artist: 'James Vasanthan', songCount: 1, artworkColors: ['#F59E0B', '#6366F1'] },
  { id: 'alb_7', title: 'Jaanu (96)', artist: 'Govind Vasantha', songCount: 1, artworkColors: ['#6366F1', '#8B5CF6'] },
  { id: 'alb_8', title: 'Thaamirabharani', artist: 'Yuvan Shankar Raja', songCount: 1, artworkColors: ['#EF4444', '#10B981'] },
  { id: 'alb_9', title: 'Rummy', artist: 'D. Imman', songCount: 1, artworkColors: ['#10B981', '#D946EF'] },
  { id: 'alb_10', title: 'Uthama Puthiran', artist: 'Vijay Antony', songCount: 1, artworkColors: ['#10B981', '#0EA5E9'] },
  { id: 'alb_11', title: 'Mandaadi', artist: 'G.V. Prakash Kumar', songCount: 1, artworkColors: ['#EC4899', '#8B5CF6'] },
];

export const BUILT_IN_ARTISTS: Artist[] = [
  { id: 'art_1', name: 'Yuvan Shankar Raja', songCount: 2, avatarColors: ['#0EA5E9', '#6366F1'] },
  { id: 'art_2', name: 'D. Imman', songCount: 2, avatarColors: ['#8B5CF6', '#F59E0B'] },
  { id: 'art_3', name: 'Harris Jayaraj', songCount: 1, avatarColors: ['#8B5CF6', '#D946EF'] },
  { id: 'art_4', name: 'A.R. Rahman', songCount: 1, avatarColors: ['#F59E0B', '#EF4444'] },
  { id: 'art_5', name: 'G.V. Prakash Kumar', songCount: 2, avatarColors: ['#EF4444', '#8B5CF6'] },
  { id: 'art_6', name: 'Vijay Antony', songCount: 2, avatarColors: ['#10B981', '#0EA5E9'] },
  { id: 'art_7', name: 'Govind Vasantha', songCount: 1, avatarColors: ['#6366F1', '#8B5CF6'] },
  { id: 'art_8', name: 'James Vasanthan', songCount: 1, avatarColors: ['#F59E0B', '#6366F1'] },
  { id: 'art_9', name: 'Vivek - Mervin', songCount: 1, avatarColors: ['#6366F1', '#10B981'] },
  { id: 'art_10', name: 'TeeJay ft Pragathi', songCount: 1, avatarColors: ['#0EA5E9', '#8B5CF6'] },
];

export const BUILT_IN_PLAYLISTS: Playlist[] = [
  {
    id: 'pl_1',
    title: 'Tamil Chartbusters',
    songCount: 16,
    durationString: '1h 14m',
    artworkColors: ['#6366F1', '#D946EF'],
    songIds: BUILT_IN_SONGS.map(s => s.id),
  },
  {
    id: 'pl_2',
    title: 'Melody Hits',
    songCount: 9,
    durationString: '42m',
    artworkColors: ['#0EA5E9', '#6366F1'],
    songIds: ['song_01', 'song_04', 'song_06', 'song_08', 'song_09', 'song_11', 'song_12', 'song_13', 'song_16'],
  },
  {
    id: 'pl_3',
    title: 'Folk & Kuthu Vibes',
    songCount: 7,
    durationString: '32m',
    artworkColors: ['#F59E0B', '#EF4444'],
    songIds: ['song_02', 'song_03', 'song_05', 'song_07', 'song_10', 'song_14', 'song_15'],
  },
];
